### PR TITLE
Update CacheAdapter.php

### PR DESCRIPTION
**Pull request by powerpbx**
As far as I can tell, this is just returning true if the path exists in cache.  What it should be doing is returning true OR false depending on if the path is a file.

### CODE REVIEW

**Comment by Lustmored** [comment]
This library in its current form is only caching files info, not directories, therefore if cache is hit then it must be file that exists (at least that was my intent). Could you provide an example or scenario where current implementation fails?

Ignoring cache on `fileExists` would be a big hit for performance in some scenarios (it's widely used method) therefore I would prefer it doesn't ignore cache.

**Comment by powerpbx** [comment]
This only tests if the path exists in cache which is not what the original Flysystem `fileExists()` method does, therefore it sometimes returns an incorrect result and will break code designed around FlySystem.

For example, if you test a directory and that path is cached it will return true, indicating that the directory is a file which is obviously an incorrect result.  If you then tried to retrieve `mimeType()` thinking this is a file it would result in an exception error.  That is how I found this problem.

If you want to cache a `fileExists()` true result I believe that would need to be a new unique hash of `$path` to identify that.  

So maybe:
```php
$item = $this->getCacheItem('some_new_unique_hash_of_$path');
if ($item->exists()) {
    return true;
}
...
```




You could also put it in `extraMetadata` variable that is included in the FlySystem fileAttributes object if you implement that.

**Comment by Lustmored** [comment]
Can you please provide and example script where the problem occurs? I simply don't see the case where this adapter will cache item that is an existing directory. But I might be missing something, I just need a test case to verify what goes wrong :)

**Comment by powerpbx** [comment]
> Can you please provide and example script where the problem occurs? I simply don't see the case where this adapter will cache item that is an existing directory. But I might be missing something, I just need a test case to verify what goes wrong :)

This is the part of my code that fails with `flysystem-v2-simple-cache-adapter` enabled. I traced it back to the `fileExists()` method.
```php
$type = $this->fs->fileExists($path) ? 'file' : 'dir';
if ($type === 'file') {
    $meta['mimetype'] => $this->fs->mimeType($path); // BOOM, exception error if $path is cached and not a file
}
```
If you are only caching `$path` on files and nothing else then it must be something on my end.  Thanks for the quick reply.  Closing this for now.

**Pull request closed without merging**
